;; This is an operating system configuration generated
;; by the graphical installer.

(use-modules (gnu)
	     (nongnu packages linux)
	     (nongnu system linux-initrd))

(use-service-modules desktop 
	             networking 
	             ssh 
	     	     xorg
		     nix)

(use-package-modules package-management)

(operating-system
  (kernel linux)
  (initrd microcode-initrd)
  (firmware (list linux-firmware))
  (locale "en_US.utf8")
  (timezone "America/Detroit")
  (keyboard-layout (keyboard-layout "us"))
  (host-name "Voyager")
  (users (cons* (user-account
                  (name "Que")
                  (comment "Que Zo'e")
                  (group "users")
                  (home-directory "/home/Que")
                  (supplementary-groups
                    '("wheel" "netdev" "audio" "video")))
                %base-user-accounts))
  (packages
    (append
      (list nix 
	    (specification->package "nss-certs"))
      %base-packages))
  (services
    (append
      (list (service gnome-desktop-service-type)
            (service openssh-service-type)
	    (service nix-service-type)
            (set-xorg-configuration
              (xorg-configuration
                (keyboard-layout keyboard-layout))))
      %desktop-services))
  (bootloader
    (bootloader-configuration
      (bootloader grub-efi-bootloader)
      (target "/boot/efi")
      (keyboard-layout keyboard-layout)))
;; Replace below this point with file from auto-generated by install  config 
  (swap-devices
    (list (uuid "14398f50-5d66-4ff3-9d8e-b706fbd9db3a")))
  (file-systems
    (cons* (file-system
             (mount-point "/boot/efi")
             (device (uuid "7211-8566" 'fat32))
             (type "vfat"))
           (file-system
             (mount-point "/")
             (device
               (uuid "7803a8db-e4fa-4109-92e3-132ea6a7db8d"
                     'ext4))
             (type "ext4"))
           (file-system
             (mount-point "/home")
             (device
               (uuid "3b81ddc2-636e-4732-ad5d-c0f942d0e17b"
                     'ext4))
             (type "ext4"))
           %base-file-systems)))
